/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventActivityIdRouteImport } from './routes/event.$activityId'
import { Route as EventActivityIdDisplayRouteImport } from './routes/event.$activityId_.display'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventActivityIdRoute = EventActivityIdRouteImport.update({
  id: '/event/$activityId',
  path: '/event/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventActivityIdDisplayRoute = EventActivityIdDisplayRouteImport.update({
  id: '/event/$activityId_/display',
  path: '/event/$activityId/display',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/$activityId': typeof EventActivityIdRoute
  '/event/$activityId/display': typeof EventActivityIdDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$activityId': typeof EventActivityIdRoute
  '/event/$activityId/display': typeof EventActivityIdDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/$activityId': typeof EventActivityIdRoute
  '/event/$activityId_/display': typeof EventActivityIdDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/event/$activityId' | '/event/$activityId/display'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/event/$activityId' | '/event/$activityId/display'
  id: '__root__' | '/' | '/event/$activityId' | '/event/$activityId_/display'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventActivityIdRoute: typeof EventActivityIdRoute
  EventActivityIdDisplayRoute: typeof EventActivityIdDisplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$activityId': {
      id: '/event/$activityId'
      path: '/event/$activityId'
      fullPath: '/event/$activityId'
      preLoaderRoute: typeof EventActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$activityId_/display': {
      id: '/event/$activityId_/display'
      path: '/event/$activityId/display'
      fullPath: '/event/$activityId/display'
      preLoaderRoute: typeof EventActivityIdDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventActivityIdRoute: EventActivityIdRoute,
  EventActivityIdDisplayRoute: EventActivityIdDisplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
