// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	CORS_ALLOWED_ORIGINS: string;
	EVENT_ROOM: DurableObjectNamespace /* EventRoom from snap-wall-api */;
}
